### ISSUE TITLE
Is there a maven repository

### ISSUE THREAD

**Issue by nbartels** [bedatadriven/gxt#1]
Your GXT fork and the changes made here is really great, but it would be much better if the jar file could be fetched from a maven repository. 

Other projects could be built upon your work and don't need to do some specials actions to get build ;)

Are there plans to put the stuff in a maven repository?

**Comment by akbertram** [comment]
Unfortunately we've since migrated away from GXT and this fork, so I won't be doing any further development on it. Feel free to re-fork!
